@startuml
actor Customer as c 
participant "Service Interface\n yours or 3rd party" as si
database CustomerDB as cdb
participant "API" as a
c -> si: browse and tests
si --> cdb: collect data
c -> si: "signs up" 
si -> cdb: saves the customer data (contact & contract details e.g. subscription)
note left of cdb: eg name, adress, contact data, payment data 
note right of cdb: we could offer a service manage the \ncustomer data (multi tenancy & saas)
c -> si: subscribe to service
si -> a: manages `/products` and `/customers`
c -> si: use service
si -> a: serve the `/products` throw interface
c -> si: manages the subscription (renew/cancel)
si -> a: /products & /customers
@enduml